language: python
sudo: false
python:
  - 2.7
  - 3.6
  - pypy
  - pypy3
matrix:
  include:
    - python: 2.7
      env: PURE_PYTHON=1
    - python: 3.6
      env: PURE_PYTHON=1
script:
  - coverage run -m zope.testrunner --test-path=src
after_success:
  - coveralls
notifications:
  email: dev-regression-tests@nextthought.com

install:
  - pip install -U pip
  - pip install -U setuptools
  - pip install -U coveralls coverage
  - pip install -U -e ".[test]"

cache: pip

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
